# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test MLAgility Using Self-Hosted Azure GPU

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: dan-selfhost-fun
    env:
      MLAGILITY_DEBUG: True
      MLAGILITY_TRACEBACK: True
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: mla
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          conda install pylint
          if [ -f setup.py ]; then pip install -e .; fi
          pip install transformers
          python -m pip check
      - name: Test with unittest
        shell: bash -el {0}
        run: |
          # Unit tests
          rm -rf ~/.cache/mlagility
          python test/database.py

          # mlagility examples
          rm -rf ~/.cache/mlagility
          python examples/model_api/hello_world.py
          rm -rf ~/.cache/mlagility
          python examples/script_api/onnx_opset.py --onnx-opset 15
          rm -rf ~/.cache/mlagility
          benchit examples/cli/scripts/hello_world.py
          rm -rf ~/.cache/mlagility
          benchit examples/cli/scripts/max_depth.py --max-depth 1
          rm -rf ~/.cache/mlagility
          benchit examples/cli/scripts/two_models.py
          rm -rf ~/.cache/mlagility
          benchit examples/cli/scripts/hello_world.py --sequence-file examples/cli/extras/example_sequence.py --build-only
          rm -rf ~/.cache/mlagility
          benchit examples/cli/onnx/sample.onnx

          # E2E tests
          rm -rf ~/.cache/mlagility
          python test/cli.py
          rm -rf ~/.cache/mlagility
          python test/analysis.py
          rm -rf ~/.cache/mlagility
          python test/model_api.py
          rm -rf ~/.cache/mlagility
          python test/analysis.py